apiVersion: v1
kind: Service
metadata:
  name: etcd-client
spec:
  ports:
  - name: etcd-client-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd

---
apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd0
  name: etcd0
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd0

---

apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd1
  name: etcd1
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd2
  name: etcd2
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd2
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd0
  labels:
    app: etcd
    etcd_node: etcd0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
      etcd_node: etcd0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: etcd
        etcd_node: etcd0
    spec:
      containers:
        - image:  quay.io/coreos/etcd:latest 
          name: etcd0
          ports:
            - containerPort: 80
              name: client
            - containerPort: 443
              name: server
              protocol: TCP
          command:
           - /usr/local/bin/etcd
           - --name
           - etcd0
           - --initial-advertise-peer-urls
           - http://etcd0:2380
           - --listen-peer-urls
           - http://0.0.0.0:2380
           - --listen-client-urls
           - http://0.0.0.0:2379
           - --advertise-client-urls
           - http://etcd0:2379
           - --initial-cluster
           - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
           - --initial-cluster-state
           - new
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd1
  labels:
    app: etcd
    etcd_node: etcd1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
      etcd_node: etcd1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: etcd
        etcd_node: etcd1
    spec:
      containers:
        - image:  quay.io/coreos/etcd:latest
          name: etcd1
          ports:
            - containerPort: 80
              name: client
            - containerPort: 443
              name: server
              protocol: TCP
          command:
           - /usr/local/bin/etcd
           - --name
           - etcd1
           - --initial-advertise-peer-urls
           - http://etcd1:2380
           - --listen-peer-urls
           - http://0.0.0.0:2380
           - --listen-client-urls
           - http://0.0.0.0:2379
           - --advertise-client-urls
           - http://etcd1:2379
           - --initial-cluster
           - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
           - --initial-cluster-state
           - new
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd2
  labels:
    app: etcd
    etcd_node: etcd2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
      etcd_node: etcd2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: etcd
        etcd_node: etcd2
    spec:
      containers:
        - image:  quay.io/coreos/etcd:latest
          name: etcd2
          ports:
            - containerPort: 80
              name: client
            - containerPort: 443
              name: server
              protocol: TCP
          command:
           - /usr/local/bin/etcd
           - --name
           - etcd2
           - --initial-advertise-peer-urls
           - http://etcd2:2380
           - --listen-peer-urls
           - http://0.0.0.0:2380
           - --listen-client-urls
           - http://0.0.0.0:2379
           - --advertise-client-urls
           - http://etcd2:2379
           - --initial-cluster
           - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
           - --initial-cluster-state
           - new
      restartPolicy: Always
