apiVersion: v1
kind: Service
metadata:
  name: db-ss
  labels:
    app: db-ss
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: db-ss

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-ss
spec:
  serviceName: "db-ss"
  replicas: 3 
  selector:
    matchLabels:
      app: db-ss
  template:
    metadata:
      labels:
        app: db-ss
    spec:
      containers:
      - name: db
        #image: severalnines/mariadb:10.1
        image: docker.io/tusharja2986/mysql-master
        ports:
        - name: mysql
          containerPort: 3306
        env:
        # kubectl create secret generic mysql-pass --from-file=password.txt
        - name: MYSQL_ROOT_PASSWORD
          value: hun123
        - name: DISCOVERY_SERVICE
          value: etcd-client:2379
        - name: XTRABACKUP_PASSWORD
          value: Xtracakuppassword
        - name: CLUSTER_NAME
          value: mariadb_db_ss
        - name: MYSQL_DATABASE
          value: m2
        - name: MYSQL_USER
          value: m2_user
        - name: MYSQL_PASSWORD
          value: m2magentopassowrd
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --readiness
          initialDelaySeconds: 120
          periodSeconds: 1
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --liveness
          initialDelaySeconds: 120
          periodSeconds: 1
        volumeMounts:
        - name: mysql-datadir
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # uncomment if using slow storageClass on AWS
      # then no need for running pv or pvc manifests
      storageClassName: slow
      resources:
        requests:
          storage: 5Gi
